version: 0.2

run-as: Linux-user-name
            
phases:
  install:
    run-as: Linux-user-name
    commands:

    finally:

  pre_build:
    run-as: Linux-user-name
    commands:

    finally:

  build:
    run-as: Linux-user-name
    commands:

    finally:

  post_build:
    run-as: Linux-user-name
    commands:

    finally:


